# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: teal
  custom_css: 
    - css/custom.css
  
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Grasper Lab University of Aberdeen'
    description: 'Constanze Hesse Grasper Lab'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '2OVqX3ofdZKRqq-bd8U7nxZPA_kP9_DIQIBqkpu8o98'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    favicon: true
    logo:
      image: "favicon.ico"
      text: "Grasper Lab"

# Site footer
footer:
  copyright:
    notice: '© {year} Constanze Hesse. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

sharing: false
show_page_nav: false
